# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-03-18 12:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hitvmm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='school',
            field=models.CharField(default='free', max_length=64),
        ),
    ]
