# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-03-18 13:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hitvmm', '0002_user_school'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experiment_id', models.IntegerField(default=0, max_length=4)),
                ('teacher_id', models.IntegerField(default=0, max_length=8)),
                ('student_id', models.IntegerField(default=0, max_length=8)),
                ('subm_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('score_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('score', models.IntegerField(default=0, max_length=3)),
                ('tatus', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TeamRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(default='free_team', max_length=64)),
                ('school', models.CharField(default='free_school', max_length=64)),
                ('teacher_id', models.IntegerField(default=0, max_length=8)),
                ('student_id', models.IntegerField(default=0, max_length=8)),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='create_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='user',
            name='identity',
            field=models.CharField(default='free', max_length=32),
        ),
    ]
