# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-03-18 15:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hitvmm', '0004_auto_20180318_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportrecord',
            name='teacher_name',
            field=models.CharField(default='free', max_length=32),
        ),
    ]
