# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-03-18 19:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hitvmm', '0005_reportrecord_teacher_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportrecord',
            name='student_name',
            field=models.CharField(default='free', max_length=32),
        ),
    ]
