# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-03-19 12:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hitvmm', '0007_reportrecord_student_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamrecord',
            name='experiment_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='identity',
            field=models.CharField(default='1', max_length=32),
        ),
    ]
