# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-03-19 13:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hitvmm', '0008_auto_20180319_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportrecord',
            name='timestamp',
            field=models.CharField(default='', max_length=32),
        ),
    ]
